#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

sudo sed -i 's/8080 default_server/80 default_server/' /etc/nginx/sites-enabled/default
sudo service nginx restart
